#!/usr/bin/env node
'use strict';

/**
 * Build the static GitHub Pages demo into /demo.
 *
 * The demo is the SAME frontend as the full app, switched to "demo" mode:
 *   • config.js          -> mode: "demo"
 *   • js/sample-data.js   -> window.DEMO_SAMPLE (44 real-distribution responses)
 *   • the data layer uses bundled sample data + localStorage (no backend)
 *
 * Output is fully static — open demo/index.html directly, or publish /demo to
 * GitHub Pages. No server, no database, no real responses collected.
 */

const fs = require('fs');
const path = require('path');
const { generate } = require('./lib/sample-generator');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'public');
const OUT = path.join(ROOT, 'demo');

// 1. Fresh copy of public/ -> demo/
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });
fs.cpSync(SRC, OUT, { recursive: true });

// 2. Sample data
const sample = generate();
const sampleJs =
  '/* Auto-generated by scripts/build-demo.js — bundled demo sample data.\n' +
  '   Reproduces the client\'s real Excel distributions (headline 84.4%). */\n' +
  'window.DEMO_SAMPLE = ' +
  JSON.stringify({ headcount: sample.headcount, responses: sample.responses }, null, 0) +
  ';\n';
fs.writeFileSync(path.join(OUT, 'js', 'sample-data.js'), sampleJs);

// 3. Demo config
const configJs =
  '/* Demo build — static, no backend. */\n' +
  'window.APP_CONFIG = { mode: "demo", demoNote: "Sample data — not the live system." };\n';
fs.writeFileSync(path.join(OUT, 'js', 'config.js'), configJs);

// 4. Inject the sample-data script tag into both pages
const inject = '<script src="js/sample-data.js"></script>';
for (const page of ['index.html', 'admin.html']) {
  const p = path.join(OUT, page);
  let html = fs.readFileSync(p, 'utf8');
  html = html.replace('<!-- DEMO_SAMPLE_INJECT -->', inject);
  fs.writeFileSync(p, html);
}

// 5. A small .nojekyll so GitHub Pages serves files verbatim, plus a notice.
fs.writeFileSync(path.join(OUT, '.nojekyll'), '');
fs.writeFileSync(
  path.join(OUT, 'DEMO-NOTICE.txt'),
  'This is a STATIC DEMO with FAKE sample data. It does not collect real ' +
    'responses and is not the production system.\n'
);

const total = sample.responses.length;
console.log(`Built static demo -> ${path.relative(ROOT, OUT)}/`);
console.log(`  • ${total} sample responses bundled (headline 84.4%).`);
console.log('  • Preview locally:  npx serve demo   (or any static server)');
console.log('  • Publish: push /demo to a gh-pages branch or set Pages source to /demo.');
